// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2jfUmLuS5nLHqfwF6umwfkUIpF3CyeAE',
    appId: '1:968634084074:web:d8683ed68413b0762b8593',
    messagingSenderId: '968634084074',
    projectId: 'ai-seller-assistant-bfd43',
    authDomain: 'ai-seller-assistant-bfd43.firebaseapp.com',
    storageBucket: 'ai-seller-assistant-bfd43.firebasestorage.app',
    measurementId: 'G-1W08KEMZWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAihPat9izsqnpPt1Rez5YLZHlFYXpyLwc',
    appId: '1:968634084074:android:660575b3f181bc4a2b8593',
    messagingSenderId: '968634084074',
    projectId: 'ai-seller-assistant-bfd43',
    storageBucket: 'ai-seller-assistant-bfd43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxJs81VLUcIAR0EJDcBrIBE-AalLLpIsk',
    appId: '1:968634084074:ios:8ed486dc09ecd2a72b8593',
    messagingSenderId: '968634084074',
    projectId: 'ai-seller-assistant-bfd43',
    storageBucket: 'ai-seller-assistant-bfd43.firebasestorage.app',
    iosBundleId: 'com.example.aiSellerAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxJs81VLUcIAR0EJDcBrIBE-AalLLpIsk',
    appId: '1:968634084074:ios:8ed486dc09ecd2a72b8593',
    messagingSenderId: '968634084074',
    projectId: 'ai-seller-assistant-bfd43',
    storageBucket: 'ai-seller-assistant-bfd43.firebasestorage.app',
    iosBundleId: 'com.example.aiSellerAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2jfUmLuS5nLHqfwF6umwfkUIpF3CyeAE',
    appId: '1:968634084074:web:6a6983b57e9593e82b8593',
    messagingSenderId: '968634084074',
    projectId: 'ai-seller-assistant-bfd43',
    authDomain: 'ai-seller-assistant-bfd43.firebaseapp.com',
    storageBucket: 'ai-seller-assistant-bfd43.firebasestorage.app',
    measurementId: 'G-43GL7FF4FH',
  );
}
